### ISSUE TITLE
Outdated Sodium

### ISSUE THREAD

**Issue by MicrocontrollersDev** [Kingili22/Fabric-Mods-for-Hypixel-SMPs#3]
The current listed version of sodium is very old and will cause problems with some mods, most noticeably EBE. I think a quick guide on how to install the latest version of Sodium through GitHub would greatly benefit this list as currently, any mod that requires the Fabric Rendering API simply will not work, including OptiFine replacements like ctm.

Writing this here because was hoping to get some discussion about this. You don’t need to compile the mod yourself, you just need to manually download a file from GitHub, so it won’t be too difficult for the user.

**Comment by Kingili22** [comment]
Guide Added!
